name: CI-CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Test Image
        run: docker build -t postman-tests .

      # Run container & generate HTML report
      - name: Run Postman Tests and Generate Report
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/etc/newman \
            postman-tests

      # Upload HTML report even if tests fail
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Production Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/testing-cicd-postman-tests:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/testing-cicd-postman-tests:latest