name: CI-CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Postman Tests (Docker) with HTML Report
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/etc/newman \
            dannydainton/newman-reporter-htmlextra \
            run Day2-Practice.postman_collection.json \
            -e New-Environment.postman_environment.json \
            -r htmlextra \
            --reporter-htmlextra-export newman-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/testing-cicd-postman-tests:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/testing-cicd-postman-tests:latest