jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Postman Tests and Generate HTML Report
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/etc/newman" \
            postman/newman:alpine \
            sh -c "npm install -g newman-reporter-htmlextra && \
                   newman run Day2-Practice.postman_collection.json \
                   -e New-Environment.postman_environment.json \
                   -r htmlextra \
                   --reporter-htmlextra-export /etc/newman/newman-report.html"

      - name: Show Files in Workspace
        run: ls -la ${{ github.workspace }}

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html